### ISSUE TITLE
Review needed

### ISSUE THREAD

**Issue by corentin521** [PolytechLyon/isi3-tp2-visiteur-bect-chambouvet-tp2#1]
Bonjour,

Pourriez vous nous donner votre avis concernant notre code et notre rapport ?

Merci d'avance

**Comment by Slashgear** [comment]
- le rapport est très bien mais pouvez vous m'expliquer le use case de ce pattern ?

- On range tout dans des packages ? (⚠️ Attention en minuscule)

- La gestion des priorité est malheureusement ratée. 😢 
Dites vous que dans 90% des cas, quand on utilise `instanceof`c'est un aveu d'échec.
On a justement mis en place le visiteur dans ce TP pour voir comment faire des visit generic sans avoir à analyser le type de noeud courant.

Je vous propose de gérer la priorité par une méthode du noeuds qui retourne un entier ? Vous avez ensuite à comparer les priorités retournée. 

Il y a également une méthode plus "tricky" à base de generic en Java mais la première solution est suffisante 😄

**Comment by corentin521** [comment]
Bonjour, 

Merci pour ce retour. Nous avons ajouté des packages et modifié le système de priorités en ajoutant une méthode retournant un entier. En quoi consiste la deuxième méthode à base de générique ?

Quant aux use cases du pattern Visitor, les voici :  

Le pattern Visiteur est utilisé lorsque l'on souhaite : 
* ajouter à des objets des fonctionnalités sans (trop) modifier leur contenu,
* éviter d'ajouter différentes opérations indépendantes en les réunissant dans une classe à part,
* réaliser des actions sur des objets qui dépendent de leur type concret.

**Comment by Slashgear** [comment]
C'est pas trop mal. 

On parlera generic dans les prochains TP
